# Generated by Django 4.1.3 on 2022-11-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moshina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yili', models.IntegerField(default=2020)),
                ('narxi', models.IntegerField(default=1)),
                ('turi', models.CharField(max_length=24)),
                ('rangi', models.CharField(max_length=25)),
                ('rasmcha', models.CharField(max_length=25)),
            ],
        ),
    ]
